ruby '>=2.5.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.2.1'

# MySQL support
gem 'mysql2'
gem 'will_paginate', '~> 3.1.7'

# Authentication
gem 'devise'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7', platform: :ruby
gem 'simple_token_authentication', '~> 1.15'
gem 'fast_jsonapi'
# gem "active_model_serializers", "~> 0.10.2"

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

# Queuing back-end
gem 'sucker_punch'

gem 'mailjet'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Use Puma as the app server
  gem 'puma', '~> 3.11'
  gem "letter_opener"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
