ruby '>=2.5.3'

gem 'rails', '~> 5.2.2.1'

# email us when exceptions happen
gem 'exception_notification'

# fast like sanic serialization
gem 'fast_jsonapi'

# MariaDB/MySQL support
gem 'mysql2'
gem 'will_paginate', '~> 3.1.7'

# Authentication
gem 'devise'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7', platform: :ruby
# Encrypt sensitive ActiveRecord attributes
gem 'symmetric-encryption'

# File attachment, uses Uppy.js XHR Uploading on the front-end
gem 'shrine', "~> 3.1"
# Binary image analyzer to determine mime type
gem 'marcel'
# Thumbnail processing
gem 'image_processing', '~> 1.9'
gem 'ruby-vips'

# Websocket client for communicating to chat server
gem 'websocket-client-simple'

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

# Queuing back-end
gem 'sucker_punch'

gem 'mailjet'

group :development, :test do
  # Use Puma as the app server
  gem 'puma', '~> 3.12'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem "letter_opener"
  gem 'rack-cors'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
